---
# title: "Setting up Python Computing Environment"
format: html
editor: visual
---

# Setting-up Python Computing Environment

## Use Google Colab

All you need is a Google account. Sign in your Google account in a browser, and navigate to Google Colab. Google Colab supports both `Python` and `R`. `Python` is the default engine. Change the engine to `R` in `Connect`-\>`change runtime type`. Then you are all set. Your file will be saved to your Google Drive or you can choose to send it to your `GitHub` account (recommended).

\
\## On your own computer

1.  **Anaconda**: Download anaconda and install using default installation options

2.  **VSC**: Download VSC and install

3.  start VSC and install VSC extensions in VSC: Python, Jupyter, intellicode

4.  (optional) **Quarto** for authoring: Download Quarto and install

5.  Start an anaconda terminal. Navigate to the file directory.

6.  Setup a conda **virtual environment**: stat1010 and install python and ipykernel engines

    `conda create -n stat1010 python ipykernel`

7.  Activate the venv: `conda activate stat1010`

8.  start VSC by typing `code .` in the anaconda terminal

9.  open/create a `.ipynb` or `.py` file.

10. Select the kernel `stat1010`

11. Run a code cell by pressing `Shift+Enter` or click the triangular play button.

12. Continue to run other cells.

13. After finishing using VSC, close the VSC, and deactivate the virtual environment in a conda terminal: `conda deactivate`

## 
